In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mat

In [2]:
pwd


'C:\\Users\\HP'

In [3]:
cd E:\PYTHON FOR DA\Multiple_Linear_Regression

E:\PYTHON FOR DA\Multiple_Linear_Regression


In [4]:
pwd

'E:\\PYTHON FOR DA\\Multiple_Linear_Regression'

In [40]:
df=pd.read_csv('50_Startups.csv')

In [41]:
df

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [44]:
X=df.iloc[:,0:4].values

In [45]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [50]:
Y=df.iloc[:,4:].values

In [51]:
Y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [93]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
l_x=LabelEncoder()
X[:,3]=l_x.fit_transform(X[:,3])

In [95]:
X

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.8000000e+01,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.7000000e+01,
        1.5137759e+05, 4.4389853e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 4.6000000e+01,
        1.0114555e+05, 4.0793454e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.5000000e+01,
        1.1867185e+05, 3.8319962e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 4.4000000e+01,
        9.1391770e+04, 3.6616842e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.2000000e+01,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.3000000e+01,
        1.4719887e+05, 1.2771682e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 4.1000000e+01,
        1.4553006e+05, 3.2387668e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 3.9000000e+01,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [96]:
X=X[:,1:]

In [98]:
X

array([[0.0000000e+00, 1.0000000e+00, 4.8000000e+01, 1.3689780e+05,
        4.7178410e+05],
       [0.0000000e+00, 0.0000000e+00, 4.7000000e+01, 1.5137759e+05,
        4.4389853e+05],
       [1.0000000e+00, 0.0000000e+00, 4.6000000e+01, 1.0114555e+05,
        4.0793454e+05],
       [0.0000000e+00, 1.0000000e+00, 4.5000000e+01, 1.1867185e+05,
        3.8319962e+05],
       [1.0000000e+00, 0.0000000e+00, 4.4000000e+01, 9.1391770e+04,
        3.6616842e+05],
       [0.0000000e+00, 1.0000000e+00, 4.2000000e+01, 9.9814710e+04,
        3.6286136e+05],
       [0.0000000e+00, 0.0000000e+00, 4.3000000e+01, 1.4719887e+05,
        1.2771682e+05],
       [1.0000000e+00, 0.0000000e+00, 4.1000000e+01, 1.4553006e+05,
        3.2387668e+05],
       [0.0000000e+00, 1.0000000e+00, 3.9000000e+01, 1.4871895e+05,
        3.1161329e+05],
       [0.0000000e+00, 0.0000000e+00, 4.0000000e+01, 1.0867917e+05,
        3.0498162e+05],
       [1.0000000e+00, 0.0000000e+00, 3.6000000e+01, 1.1059411e+05,
        2.29

In [99]:
from sklearn.cross_validation import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [100]:
from sklearn.linear_model import LinearRegression
l=LinearRegression()
l.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [101]:
Y_pred=l.predict(X_test)

In [102]:
Y_pred

array([[100815.65143643],
       [141065.32323456],
       [140351.4842569 ],
       [ 69602.81317407],
       [171849.80561966],
       [115796.48839866],
       [ 64138.93341569],
       [ 88177.53284686],
       [114766.47156368],
       [165080.49074038]])

In [103]:
from sklearn.metrics import r2_score

In [105]:
r2_score(Y_test,Y_pred)

0.9217139712234428

In [106]:
#applying backward elimination
import statsmodels.formula.api as sm
X=np.append(arr=np.ones((50,1)).astype(int),values=X,axis=1)


In [124]:
X_train

array([[1.0000000e+00, 0.0000000e+00, 1.5000000e+01, 1.0305749e+05,
        2.1463481e+05],
       [0.0000000e+00, 1.0000000e+00, 1.3000000e+01, 8.5047440e+04,
        2.0551764e+05],
       [1.0000000e+00, 0.0000000e+00, 2.5000000e+01, 1.4413598e+05,
        1.3405007e+05],
       [0.0000000e+00, 0.0000000e+00, 1.4000000e+01, 1.5769392e+05,
        2.1079767e+05],
       [1.0000000e+00, 0.0000000e+00, 3.1000000e+01, 1.1417579e+05,
        2.9491957e+05],
       [1.0000000e+00, 0.0000000e+00, 4.1000000e+01, 1.4553006e+05,
        3.2387668e+05],
       [1.0000000e+00, 0.0000000e+00, 3.8000000e+01, 1.5654742e+05,
        2.5651292e+05],
       [0.0000000e+00, 1.0000000e+00, 2.0000000e+00, 1.2415304e+05,
        1.9039300e+03],
       [0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 5.1743150e+04,
        0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 2.0000000e+01, 1.5303206e+05,
        1.0713838e+05],
       [0.0000000e+00, 1.0000000e+00, 3.7000000e+01, 1.2261684e+05,
        2.61

In [134]:
X_opt=X_train[:,[0,1,2,3,4]]


In [135]:
r_OLS=sm.OLS(endog=Y_train,exog=X_opt).fit()
r_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.987
Model:                            OLS   Adj. R-squared:                  0.985
Method:                 Least Squares   F-statistic:                     536.2
Date:                Mon, 21 Jan 2019   Prob (F-statistic):           5.07e-32
Time:                        19:25:06   Log-Likelihood:                -436.42
No. Observations:                  40   AIC:                             882.8
Df Residuals:                      35   BIC:                             891.3
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          -931.0072   5806.377     -0.160      0.874   -1.27e+04    1.09e+04
x2          3444.1814   5177.922      0.665      0.510   -7067.558     1.4e+04
x3          2094.8875    240.881      8.697      0.000    1605.874    2583.901
x4             0.3426      0.039      8.696      0.000       0.263       0.423
x5             0.0822      0.026      3.176      0.003       0.030       0.135
==============================================================================
Omnibus:                        3.078   Durbin-Watson:                   2.146
Prob(Omnibus):                  0.215   Jarque-Bera (JB):                2.167
Skew:                          -0.558   Prob(JB):                        0.338
Kurtosis:                       3.232   Cond. No.                     7.63e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.63e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [139]:
X_opt=X_train[:,[0,2,3,4]]
r_OLS=sm.OLS(endog=Y_train,exog=X_opt).fit()
r_OLS.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.987
Model:                            OLS   Adj. R-squared:                  0.986
Method:                 Least Squares   F-statistic:                     680.7
Date:                Mon, 21 Jan 2019   Prob (F-statistic):           2.26e-33
Time:                        19:26:51   Log-Likelihood:                -436.67
No. Observations:                  40   AIC:                             881.3
Df Residuals:                      36   BIC:                             888.1
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1         -2470.4143   5283.819     -0.468      0.643   -1.32e+04    8245.668
x2          2119.9201    236.073      8.980      0.000    1641.142    2598.698
x3             0.3508      0.037      9.436      0.000       0.275       0.426
x4             0.0819      0.026      3.190      0.003       0.030       0.134
==============================================================================
Omnibus:                        2.068   Durbin-Watson:                   2.122
Prob(Omnibus):                  0.356   Jarque-Bera (JB):                1.422
Skew:                          -0.460   Prob(JB):                        0.491
Kurtosis:                       3.093   Cond. No.                     6.21e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.21e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [140]:
X_opt=X_train[:,[2,3,4]]
r_OLS=sm.OLS(endog=Y_train,exog=X_opt).fit()
r_OLS.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.987
Model:                            OLS   Adj. R-squared:                  0.986
Method:                 Least Squares   F-statistic:                     927.1
Date:                Mon, 21 Jan 2019   Prob (F-statistic):           7.56e-35
Time:                        19:26:54   Log-Likelihood:                -436.79
No. Observations:                  40   AIC:                             879.6
Df Residuals:                      37   BIC:                             884.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          2139.5403    229.847      9.309      0.000    1673.826    2605.255
x2             0.3469      0.036      9.675      0.000       0.274       0.420
x3             0.0790      0.025      3.207      0.003       0.029       0.129
==============================================================================
Omnibus:                        1.914   Durbin-Watson:                   2.152
Prob(Omnibus):                  0.384   Jarque-Bera (JB):                1.325
Skew:                          -0.445   Prob(JB):                        0.516
Kurtosis:                       3.062   Cond. No.                     2.73e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.73e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [141]:
X_opt

array([[1.5000000e+01, 1.0305749e+05, 2.1463481e+05],
       [1.3000000e+01, 8.5047440e+04, 2.0551764e+05],
       [2.5000000e+01, 1.4413598e+05, 1.3405007e+05],
       [1.4000000e+01, 1.5769392e+05, 2.1079767e+05],
       [3.1000000e+01, 1.1417579e+05, 2.9491957e+05],
       [4.1000000e+01, 1.4553006e+05, 3.2387668e+05],
       [3.8000000e+01, 1.5654742e+05, 2.5651292e+05],
       [2.0000000e+00, 1.2415304e+05, 1.9039300e+03],
       [1.0000000e+00, 5.1743150e+04, 0.0000000e+00],
       [2.0000000e+01, 1.5303206e+05, 1.0713838e+05],
       [3.7000000e+01, 1.2261684e+05, 2.6177623e+05],
       [1.7000000e+01, 1.1564128e+05, 9.1131240e+04],
       [1.8000000e+01, 1.2921961e+05, 4.6085250e+04],
       [2.8000000e+01, 1.2159755e+05, 2.6434606e+05],
       [7.0000000e+00, 9.6189630e+04, 1.4800111e+05],
       [2.6000000e+01, 1.1386730e+05, 2.9866447e+05],
       [4.0000000e+00, 1.2738230e+05, 3.5534170e+04],
       [3.9000000e+01, 1.4871895e+05, 3.1161329e+05],
       [3.2000000e+01, 1.354

In [146]:
l.fit(X_opt,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [150]:
y_pred = l.predict(X_test[:,[2,3,4]])

In [151]:
r2_score(Y_test,y_pred)

0.9283649221698026

In [152]:
np.mean(abs(y_pred - Y_test))

7657.168832576024